# Generated by Django 3.1.1 on 2022-11-14 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('line', models.CharField(max_length=64)),
                ('kpi', models.CharField(max_length=16)),
                ('hour', models.DateTimeField()),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.deviation')),
            ],
        ),
    ]
