# Generated by Django 3.1.1 on 2022-11-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=64)),
                ('shift_date', models.DateField()),
                ('shift_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name', models.CharField(max_length=32)),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('text_value', models.CharField(blank=True, max_length=32, null=True)),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.shift')),
            ],
        ),
        migrations.AlterField(
            model_name='deviation',
            name='kpi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.kpi'),
        ),
    ]
