# Generated by Django 3.1.1 on 2022-11-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_auto_20221114_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=64)),
                ('number_of_shifts', models.IntegerField()),
            ],
        ),
    ]
