# Generated by Django 3.1.1 on 2022-11-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_shiftmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviation',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
