# Generated by Django 3.1.1 on 2022-11-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0006_auto_20221115_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviation',
            name='hour',
        ),
    ]
