# Generated by Django 3.1.1 on 2022-11-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0007_remove_deviation_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviation',
            name='hour',
            field=models.IntegerField(null=True),
        ),
    ]
