# Generated by Django 3.1.1 on 2022-11-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0008_deviation_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=32)),
                ('twx_name_1', models.CharField(max_length=32)),
                ('twx_name_2', models.CharField(max_length=32)),
                ('number_of_shifts', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='line',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='shift_date',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='shift_name',
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_start',
            field=models.DateTimeField(null=True),
        ),
    ]
