# Generated by Django 3.1.1 on 2022-11-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0009_auto_20221121_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_team',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
