# Generated by Django 3.1.1 on 2022-11-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0010_shift_shift_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('result', models.FloatField()),
                ('data', models.JSONField()),
                ('kpi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.kpi')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.line')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.shift')),
            ],
        ),
        migrations.DeleteModel(
            name='ShiftModel',
        ),
        migrations.RemoveField(
            model_name='deviation',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='deviation',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='deviation',
            name='line',
        ),
        migrations.RemoveField(
            model_name='deviation',
            name='shift',
        ),
        migrations.AddField(
            model_name='action',
            name='action_text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='level_of_escalation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviation',
            name='hour_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.hourresult'),
        ),
    ]
