# Generated by Django 3.1.1 on 2022-11-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0012_dmsrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='breaks',
            field=models.JSONField(null=True),
        ),
    ]
