# Generated by Django 3.1.1 on 2022-11-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0013_line_breaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='limits',
            field=models.JSONField(null=True),
        ),
    ]
