# Generated by Django 3.1.1 on 2022-11-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0014_line_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourresult',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
