# Generated by Django 3.1.1 on 2022-11-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0015_auto_20221122_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_per_day',
            field=models.IntegerField(null=True),
        ),
    ]
