# Generated by Django 3.1.1 on 2022-11-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0017_auto_20221122_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='dlp1',
            field=models.JSONField(null=True),
        ),
    ]
