# Generated by Django 3.1.1 on 2022-11-23 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0018_line_dlp1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='deviation',
        ),
        migrations.AddField(
            model_name='action',
            name='deviation_hour_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.hourresult'),
        ),
        migrations.AddField(
            model_name='hourresult',
            name='deviation',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Deviation',
        ),
    ]
