# Generated by Django 3.1.1 on 2022-12-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0019_auto_20221123_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('frequency', models.CharField(blank=True, max_length=32, null=True)),
                ('db_name', models.CharField(blank=True, max_length=32)),
                ('db_table', models.CharField(blank=True, max_length=128)),
                ('select_part', models.CharField(blank=True, max_length=1024)),
                ('where_part', models.CharField(blank=True, max_length=1024)),
                ('left_join_part', models.CharField(blank=True, max_length=1024)),
                ('group_by_part', models.CharField(blank=True, max_length=1024)),
                ('order_by_part', models.CharField(blank=True, max_length=1024)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.line')),
            ],
        ),
    ]
