# Generated by Django 3.1.1 on 2022-12-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0021_calculation_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='db_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='group_by_part',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='left_join_part',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='order_by_part',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='where_part',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
