# Generated by Django 3.1.1 on 2022-12-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0023_auto_20221205_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='deviation_hour_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.calculationresult'),
        ),
        migrations.DeleteModel(
            name='HourResult',
        ),
    ]
