# Generated by Django 3.1.1 on 2022-12-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0024_auto_20221205_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
