# Generated by Django 3.1.1 on 2022-12-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0025_delete_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculationResult',
        ),
    ]
