# Generated by Django 3.1.1 on 2022-12-05 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0026_delete_calculationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('result', models.FloatField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('calculation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.calculation')),
            ],
        ),
    ]
