# Generated by Django 3.1.1 on 2022-12-06 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0027_calculationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='work_center',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='PartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.CharField(blank=True, max_length=32)),
                ('setup_time', models.FloatField()),
                ('processing_time', models.FloatField()),
                ('tg_max_time', models.FloatField()),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.line')),
            ],
        ),
    ]
