# Generated by Django 3.1.1 on 2022-12-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0028_auto_20221206_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='breaks',
        ),
        migrations.RemoveField(
            model_name='line',
            name='dlp1',
        ),
        migrations.RemoveField(
            model_name='line',
            name='limits',
        ),
        migrations.CreateModel(
            name='LinePerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_value', models.FloatField()),
                ('kpi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.kpi')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.line')),
            ],
        ),
        migrations.CreateModel(
            name='LineLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lte', models.BooleanField(default=False)),
                ('is_gte', models.BooleanField(default=False)),
                ('is_equal', models.BooleanField(default=False)),
                ('limit_value', models.FloatField()),
                ('kpi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.kpi')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.line')),
            ],
        ),
        migrations.CreateModel(
            name='LineBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.TimeField()),
                ('break_end', models.TimeField()),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.line')),
            ],
        ),
    ]
