# Generated by Django 3.1.1 on 2022-12-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0029_auto_20221206_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='short_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='line',
            name='twx_name_1',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='line',
            name='twx_name_2',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='line',
            name='work_center',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
