# Generated by Django 3.1.1 on 2022-12-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0030_auto_20221206_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='with_part',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
