# Generated by Django 3.1.1 on 2022-12-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0033_changeover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineBreak',
            new_name='LineBreakTemplate',
        ),
    ]
