# Generated by Django 3.1.1 on 2022-12-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0036_auto_20221206_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineBreak',
        ),
    ]
