# Generated by Django 3.1.1 on 2022-12-06 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0037_delete_linebreak'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.DateTimeField()),
                ('break_end', models.DateTimeField()),
                ('line', models.IntegerField(null=True)),
            ],
        ),
    ]
