# Generated by Django 3.1.1 on 2022-12-06 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0039_auto_20221206_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebreak',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.line'),
        ),
    ]
