# Generated by Django 3.1.1 on 2023-01-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0040_auto_20221206_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='line',
        ),
        migrations.RemoveField(
            model_name='calculationresult',
            name='calculation',
        ),
        migrations.RemoveField(
            model_name='changeover',
            name='line',
        ),
        migrations.RemoveField(
            model_name='changeover',
            name='next_part',
        ),
        migrations.RemoveField(
            model_name='changeover',
            name='previous_part',
        ),
        migrations.RemoveField(
            model_name='downtime',
            name='line',
        ),
        migrations.RemoveField(
            model_name='linebreak',
            name='line',
        ),
        migrations.RemoveField(
            model_name='linebreaktemplate',
            name='line',
        ),
        migrations.RemoveField(
            model_name='linelimit',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='linelimit',
            name='line',
        ),
        migrations.RemoveField(
            model_name='lineperformance',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='lineperformance',
            name='line',
        ),
        migrations.RemoveField(
            model_name='partdata',
            name='line',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='Calculation',
        ),
        migrations.DeleteModel(
            name='CalculationResult',
        ),
        migrations.DeleteModel(
            name='Changeover',
        ),
        migrations.DeleteModel(
            name='Downtime',
        ),
        migrations.DeleteModel(
            name='KPI',
        ),
        migrations.DeleteModel(
            name='Line',
        ),
        migrations.DeleteModel(
            name='LineBreak',
        ),
        migrations.DeleteModel(
            name='LineBreakTemplate',
        ),
        migrations.DeleteModel(
            name='LineLimit',
        ),
        migrations.DeleteModel(
            name='LinePerformance',
        ),
        migrations.DeleteModel(
            name='PartData',
        ),
    ]
