# Generated by Django 3.1.1 on 2023-01-12 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0042_auto_20230112_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorsAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_start', models.DateTimeField()),
                ('interval_end', models.DateTimeField()),
                ('operators_count', models.IntegerField()),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.line')),
            ],
        ),
    ]
