# Generated by Django 3.1.1 on 2023-01-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0044_detailedoperatorsattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedoperatorsattendance',
            name='interval_end',
        ),
    ]
