# Generated by Django 3.1.1 on 2023-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0045_remove_detailedoperatorsattendance_interval_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedoperatorsattendance',
            name='interval_end',
            field=models.DateTimeField(null=True),
        ),
    ]
