# Generated by Django 3.1.1 on 2023-01-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0046_detailedoperatorsattendance_interval_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorsattendance',
            name='operators_count',
        ),
        migrations.AddField(
            model_name='operatorsattendance',
            name='worker_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operatorsattendance',
            name='worker_type',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operatorsattendance',
            name='interval_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='DetailedOperatorsAttendance',
        ),
    ]
