# Generated by Django 3.1.1 on 2023-01-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0048_auto_20230118_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation_id', models.BigIntegerField()),
                ('interval_beginning', models.DateTimeField()),
                ('interval_end', models.DateTimeField()),
                ('kpi', models.CharField(max_length=32)),
                ('target_value', models.FloatField()),
                ('actual_value', models.FloatField()),
                ('details', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TWXDowntimeReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twx_downtime_reason', models.CharField(blank=True, max_length=1024)),
                ('deviation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.deviation')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_beginning', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('five_s_done', models.BooleanField(default=True)),
                ('handover_confirmed', models.BooleanField(default=True)),
                ('text_info_1', models.CharField(blank=True, max_length=2048, null=True)),
                ('text_info_2', models.CharField(blank=True, max_length=2048, null=True)),
                ('shift_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.line')),
            ],
        ),
    ]
