# Generated by Django 3.1.1 on 2023-01-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0049_deviation_shiftchange_twxdowntimereason'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='KPItarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.kpi')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.line')),
            ],
        ),
    ]
