# Generated by Django 3.1.1 on 2023-01-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0050_kpi_kpitarget'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KPItarget',
            new_name='LineKPItarget',
        ),
    ]
