# Generated by Django 3.1.1 on 2023-01-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0051_auto_20230123_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='api_alias',
            field=models.CharField(default='', max_length=64),
        ),
    ]
