# Generated by Django 3.1.1 on 2023-01-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0053_linekpitarget_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TWXDowntimeReason',
        ),
    ]
