# Generated by Django 3.1.1 on 2023-01-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0054_delete_twxdowntimereason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviation',
            name='actual_value',
        ),
        migrations.RemoveField(
            model_name='deviation',
            name='interval_beginning',
        ),
        migrations.RemoveField(
            model_name='deviation',
            name='interval_end',
        ),
        migrations.RemoveField(
            model_name='deviation',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='deviation',
            name='target_value',
        ),
    ]
