# Generated by Django 3.1.1 on 2023-02-06 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0057_auto_20230206_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorsabsence',
            name='line',
        ),
        migrations.AddField(
            model_name='operatorsabsence',
            name='absence_category',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='operatorsabsence',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.area'),
        ),
    ]
