# Generated by Django 3.1.1 on 2023-02-06 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0058_auto_20230206_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftleader',
            name='line',
        ),
        migrations.AddField(
            model_name='shiftleader',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.area'),
        ),
    ]
