# Generated by Django 3.1.1 on 2023-02-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0059_auto_20230206_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='thingworx_name',
            field=models.CharField(default='dummy', max_length=128),
            preserve_default=False,
        ),
    ]
