# Generated by Django 3.1.1 on 2023-03-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0060_line_thingworx_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftchange',
            name='five_s_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shiftchange',
            name='handover_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
