# Generated by Django 3.1.1 on 2022-08-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=1)),
                ('shift_date', models.DateField()),
                ('available_minutes', models.IntegerField(default=480)),
            ],
        ),
    ]
