# Generated by Django 3.1.1 on 2022-08-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obc4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityhelper',
            name='shift_order',
            field=models.IntegerField(null=True),
        ),
    ]
