# Generated by Django 3.1.1 on 2022-12-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obc4', '0003_auto_20221208_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebookaction',
            name='station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
