# Generated by Django 3.1.1 on 2022-08-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityNokDescription',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nok_button', models.CharField(db_column='NOK_BUTTON', max_length=255)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=255)),
            ],
        ),
    ]
