# Generated by Django 3.1.2 on 2021-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_limit', models.DateTimeField(blank=True, null=True)),
                ('start_limit', models.DateTimeField(blank=True, null=True)),
                ('production_load', models.JSONField()),
                ('breaks', models.JSONField()),
                ('worktime', models.JSONField()),
            ],
        ),
    ]
