# Generated by Django 3.1.2 on 2022-03-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_order', models.IntegerField()),
                ('column_name', models.CharField(max_length=255)),
                ('column_model_name', models.CharField(max_length=255)),
                ('column_in_model', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(null=True)),
                ('specific_numer', models.IntegerField(null=True)),
                ('downtime_date', models.DateTimeField()),
                ('shift', models.CharField(max_length=10)),
                ('recorded_by', models.CharField(max_length=255)),
                ('line', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=255)),
                ('material_number', models.CharField(max_length=255)),
                ('downtime', models.CharField(max_length=255)),
                ('downtime_start', models.DateTimeField()),
                ('downtime_end', models.DateTimeField()),
                ('train_driver', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('production_note', models.CharField(max_length=255)),
                ('decoded_by', models.CharField(max_length=255)),
                ('logistics_category', models.CharField(max_length=255)),
                ('logistics_downtime', models.CharField(max_length=255)),
                ('logistics_note', models.CharField(max_length=255)),
                ('downtime_rootcause', models.CharField(max_length=255)),
                ('corrective_action', models.CharField(max_length=255)),
                ('rca_analysis', models.BooleanField(default=False)),
                ('method_used', models.CharField(max_length=255)),
                ('responsible', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainCircuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductionPlanner',
        ),
        migrations.AddField(
            model_name='downtime',
            name='production_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.productionarea'),
        ),
        migrations.AddField(
            model_name='downtime',
            name='train_circuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.traincircuit', to_field='number'),
        ),
    ]
