# Generated by Django 3.1.1 on 2022-03-02 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0002_auto_20220302_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('production_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.productionarea')),
            ],
        ),
        migrations.AddField(
            model_name='productionarea',
            name='responsible',
            field=models.ManyToManyField(related_name='production_area', to='logistics.Profile'),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.line', to_field='name'),
        ),
    ]
