# Generated by Django 3.1.1 on 2022-03-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20220302_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('is_boolean', models.BooleanField(default=False)),
                ('is_text', models.BooleanField(default=False)),
                ('is_number', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.downtimeattribute')),
            ],
        ),
    ]
