# Generated by Django 3.1.1 on 2022-03-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_attributevalue_downtimeattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='is_boolean',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='is_number',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='is_text',
        ),
        migrations.AddField(
            model_name='downtimeattribute',
            name='is_boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downtimeattribute',
            name='is_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downtimeattribute',
            name='is_text',
            field=models.BooleanField(default=False),
        ),
    ]
