# Generated by Django 3.1.1 on 2022-03-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_auto_20220303_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.DeleteModel(
            name='DowntimeAttribute',
        ),
    ]
