# Generated by Django 3.1.2 on 2022-03-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_auto_20220303_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('specification', models.CharField(max_length=255)),
            ],
        ),
    ]
