# Generated by Django 3.1.1 on 2022-03-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_categoryspecification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorySpecification',
        ),
        migrations.AlterField(
            model_name='downtime',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
