# Generated by Django 3.1.2 on 2022-03-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_auto_20220303_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='corrective_action',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='decoded_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='downtime_rootcause',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='logistics_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='logistics_downtime',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='logistics_note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='method_used',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='responsible',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
