# Generated by Django 3.1.1 on 2022-03-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_auto_20220309_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downtime',
            old_name='downtime',
            new_name='is_downtime_by_logistics',
        ),
        migrations.AddField(
            model_name='downtime',
            name='is_downtime_by_production',
            field=models.BooleanField(default=True),
        ),
    ]
