# Generated by Django 3.1.1 on 2022-03-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_auto_20220311_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='external_downtime_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='downtime',
            name='external_line',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='downtime',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
