# Generated by Django 3.1.1 on 2022-03-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_auto_20220315_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='logistics_deduction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
