# Generated by Django 3.1.1 on 2022-03-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_emailnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='note_by_production',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
