# Generated by Django 3.1.1 on 2022-03-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_auto_20220316_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='downtime_date',
            field=models.DateTimeField(verbose_name='Datum'),
        ),
    ]
