# Generated by Django 3.1.1 on 2022-03-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0020_auto_20220316_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='notify_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='notify_local_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.profile'),
        ),
    ]
