# Generated by Django 3.1.2 on 2022-03-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0022_auto_20220322_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
