# Generated by Django 3.1.1 on 2022-04-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0024_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
