# Generated by Django 3.1.1 on 2022-04-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0025_delete_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_beginning', models.DateTimeField()),
                ('team', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
