# Generated by Django 3.1.1 on 2021-06-15 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0003_auto_20210615_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimefromline',
            name='beginning',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 15, 9, 52, 792341)),
        ),
        migrations.AlterField(
            model_name='downtimefromline',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 15, 9, 52, 792383)),
        ),
    ]
