# Generated by Django 3.1.1 on 2021-06-15 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0004_auto_20210615_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimefromline',
            name='beginning',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 15, 10, 1, 692974)),
        ),
        migrations.AlterField(
            model_name='downtimefromline',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 15, 10, 1, 692998)),
        ),
    ]
