# Generated by Django 3.1.2 on 2021-06-16 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0011_auto_20210615_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimefromline',
            name='beginning',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 8, 42, 47, 843588)),
        ),
        migrations.AlterField(
            model_name='downtimefromline',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downtimefromline',
            name='downtime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downtimefromline',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 8, 42, 47, 843623)),
        ),
        migrations.AlterField(
            model_name='downtimefromline',
            name='station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
