# Generated by Django 3.1.2 on 2021-06-16 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0012_auto_20210616_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downtimefromline',
            name='beginning',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 9, 11, 14, 34555)),
        ),
        migrations.AlterField(
            model_name='downtimefromline',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 9, 11, 14, 34577)),
        ),
    ]
