# Generated by Django 3.1.2 on 2021-06-17 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0013_auto_20210616_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downtimefromline',
            name='beginning',
        ),
        migrations.RemoveField(
            model_name='downtimefromline',
            name='end',
        ),
        migrations.AddField(
            model_name='downtimefromline',
            name='beginning_t',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 9, 54, 38, 81231)),
        ),
        migrations.AddField(
            model_name='downtimefromline',
            name='end_t',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 9, 54, 38, 81271)),
        ),
    ]
