# Generated by Django 3.1.2 on 2021-06-17 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0014_auto_20210617_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimefromline',
            name='uploaded_to_xlsx',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='downtimefromline',
            name='beginning_t',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 10, 24, 8, 603645)),
        ),
        migrations.AlterField(
            model_name='downtimefromline',
            name='end_t',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 10, 24, 8, 603678)),
        ),
    ]
