# Generated by Django 3.1.2 on 2021-10-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0039_auto_20210624_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('color_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
