# Generated by Django 3.1.2 on 2021-11-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0040_categorycolors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticDowntime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downtime_start', models.DateTimeField(auto_now_add=True)),
                ('downtime_end', models.DateTimeField(blank=True, null=True)),
                ('downtime_in_progress', models.BooleanField(default=True)),
                ('downtime_from_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fp09.downtimefromline')),
            ],
        ),
    ]
