# Generated by Django 3.1.2 on 2021-11-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0041_automaticdowntime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticdowntime',
            name='downtime_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
