# Generated by Django 3.1.2 on 2021-11-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0043_auto_20211111_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutomaticDowntime',
        ),
    ]
