# Generated by Django 3.1.1 on 2021-11-15 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0044_delete_automaticdowntime'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairedDowntime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_code', models.CharField(blank=True, max_length=64, null=True)),
                ('downtime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fp09.downtimefromline')),
            ],
        ),
    ]
