# Generated by Django 3.1.1 on 2021-11-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0045_paireddowntime'),
    ]

    operations = [
        migrations.AddField(
            model_name='paireddowntime',
            name='alarm_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paireddowntime',
            name='alarm_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='paireddowntime',
            name='downtime_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
