# Generated by Django 3.1.1 on 2021-11-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0046_auto_20211115_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paireddowntime',
            name='alarm_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paireddowntime',
            name='alarm_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
