# Generated by Django 3.1.2 on 2021-11-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0047_auto_20211115_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeFromLineClone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('downtime', models.CharField(blank=True, max_length=255, null=True)),
                ('beginning_t', models.DateTimeField()),
                ('end_t', models.DateTimeField(null=True)),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('uploaded_to_xlsx', models.BooleanField(default=False)),
                ('uid', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
