# Generated by Django 3.1.2 on 2021-12-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0048_downtimefromlineclone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopLineAlarms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarmcode_id', models.CharField(blank=True, max_length=255, null=True)),
                ('station', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
