# Generated by Django 3.1.2 on 2022-02-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0049_stoplinealarms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('konstrukcni_varianta', models.CharField(blank=True, max_length=255, null=True)),
                ('typ_krouzku', models.CharField(blank=True, max_length=255, null=True)),
                ('typ_zavitu', models.CharField(blank=True, max_length=255, null=True)),
                ('barva', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
