# Generated by Django 3.1.1 on 2022-04-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0050_typedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('info', models.CharField(max_length=32)),
            ],
        ),
    ]
