# Generated by Django 3.1.1 on 2022-08-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0051_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBookAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('one_time_activity', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('responsible', models.CharField(blank=True, max_length=128)),
                ('planned_end', models.DateField(null=True)),
                ('finished_at', models.DateField(null=True)),
                ('created_by', models.CharField(blank=True, max_length=128)),
                ('updated_by', models.CharField(blank=True, max_length=128)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fp09.station')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBookActionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('planned_end', models.DateField(null=True)),
                ('finished_at', models.DateField(null=True)),
                ('service_book_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fp09.servicebookaction')),
            ],
        ),
    ]
