# Generated by Django 3.1.1 on 2022-08-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0053_auto_20220815_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebookaction',
            name='priority',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
