# Generated by Django 3.1.1 on 2022-08-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0054_servicebookaction_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebookactionentry',
            name='finished_at',
        ),
        migrations.AddField(
            model_name='station',
            name='ordering',
            field=models.IntegerField(null=True),
        ),
    ]
