# Generated by Django 3.1.1 on 2022-09-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp09', '0055_auto_20220819_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebookactionentry',
            name='owner',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
