# Generated by Django 3.1.2 on 2021-07-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mach', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Station',
            new_name='Machines',
        ),
    ]
