# Generated by Django 3.1.2 on 2022-04-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mach', '0002_auto_20210719_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machines',
            new_name='Station',
        ),
    ]
