# Generated by Django 3.1.2 on 2022-04-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mach', '0004_auto_20220411_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='color',
            field=models.CharField(default='rgb(157 157 157', max_length=32),
        ),
    ]
