# Generated by Django 3.1.1 on 2022-04-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mach', '0006_auto_20220412_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimefromline',
            name='uid',
            field=models.BigIntegerField(default=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downtimefromline',
            name='end_t',
            field=models.DateTimeField(null=True),
        ),
    ]
