# Generated by Django 3.1.1 on 2022-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_fp09', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='codename',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
