# Generated by Django 3.1.1 on 2022-06-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_fp09', '0003_dummydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummydata',
            name='color',
            field=models.CharField(default='black', max_length=32),
            preserve_default=False,
        ),
    ]
