# Generated by Django 3.1.1 on 2022-06-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_fp09', '0005_chart_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
