# Generated by Django 3.1.1 on 2022-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_fp09', '0007_chart_modifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='type',
            field=models.CharField(default='column', max_length=32),
            preserve_default=False,
        ),
    ]
