# Generated by Django 3.1.1 on 2022-06-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_fp09', '0009_auto_20220616_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ps_fp09.charttype'),
        ),
    ]
