# Generated by Django 3.1.1 on 2022-06-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_fp09', '0010_auto_20220616_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='charttype',
            name='icon_path',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
