# Generated by Django 3.1.1 on 2022-12-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_fp09', '0011_charttype_icon_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyData',
        ),
    ]
