# Generated by Django 3.1.1 on 2023-02-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=32)),
                ('team_uuid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='KPIentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name', models.CharField(max_length=32)),
                ('kpi_uuid', models.CharField(max_length=128)),
                ('kpi_value_uuid_actual', models.CharField(max_length=128)),
                ('kpi_value_uuid_target', models.CharField(max_length=128)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='valuestreamer.team')),
            ],
        ),
    ]
