# Generated by Django 3.0.6 on 2020-07-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_auto_20200708_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='priority',
        ),
    ]
