# Generated by Django 3.0.6 on 2020-07-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_auto_20200708_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ManyToManyField(blank=True, null=True, to='engagement.Questionnaire'),
        ),
    ]
