# Generated by Django 3.0.6 on 2020-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0006_auto_20200708_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ManyToManyField(blank=True, null=True, related_name='question', to='engagement.Questionnaire'),
        ),
    ]
