# Generated by Django 3.0.6 on 2020-07-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0007_auto_20200720_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ManyToManyField(blank=True, related_name='question', to='engagement.Questionnaire'),
        ),
    ]
