# Generated by Django 3.0.6 on 2020-08-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0008_auto_20200728_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='AnsweredQuestionnaire',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
