# Generated by Django 3.0.6 on 2020-08-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0009_auto_20200804_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
