# Generated by Django 3.0.6 on 2020-08-05 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engagement', '0010_remove_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='boolean_answer',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='numeric_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_answer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='type_of_answer',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='SurveyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_interviewer', models.BooleanField(blank=True, default=False, null=True)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='interviewee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewee', to='engagement.SurveyProfile'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='engagement.SurveyProfile'),
        ),
    ]
