# Generated by Django 3.0.6 on 2020-08-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0011_auto_20200805_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='filled_in',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
