# Generated by Django 2.1.15 on 2020-08-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0017_auto_20200805_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
