# Generated by Django 2.1.15 on 2020-08-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0018_auto_20200805_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
    ]
