# Generated by Django 2.1.15 on 2020-08-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0019_remove_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_questionnaire',
            field=models.ManyToManyField(blank=True, related_name='section_questionnaire', to='engagement.QuestionnaireTemplate'),
        ),
    ]
