# Generated by Django 2.1.15 on 2020-08-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0021_auto_20200805_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='questionnaire',
        ),
    ]
