# Generated by Django 2.1.15 on 2020-08-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0022_remove_section_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_questionnaire',
            field=models.ManyToManyField(blank=True, to='engagement.QuestionnaireTemplate'),
        ),
    ]
