# Generated by Django 2.1.15 on 2020-08-10 15:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0025_rangedanswer_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='detail_of_answer',
        ),
        migrations.RemoveField(
            model_name='rangedanswer',
            name='string_high',
        ),
        migrations.RemoveField(
            model_name='rangedanswer',
            name='string_low',
        ),
        migrations.RemoveField(
            model_name='rangedanswer',
            name='string_zero',
        ),
        migrations.AddField(
            model_name='rangedanswer',
            name='strings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
        ),
    ]
