# Generated by Django 2.1.15 on 2020-08-10 15:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0026_auto_20200810_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangedanswer',
            name='strings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
