# Generated by Django 2.1.15 on 2020-08-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0028_auto_20200810_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rangedanswer',
            name='steps',
        ),
        migrations.AlterField(
            model_name='rangedanswer',
            name='numeric_zero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
