# Generated by Django 2.1.15 on 2020-08-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0029_auto_20200810_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangedanswer',
            name='numeric_high',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rangedanswer',
            name='numeric_low',
            field=models.IntegerField(null=True),
        ),
    ]
