# Generated by Django 2.1.15 on 2020-08-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0031_auto_20200811_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='sent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
