# Generated by Django 2.1.15 on 2020-08-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0032_questionnaire_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
