# Generated by Django 3.0.6 on 2020-08-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0033_auto_20200812_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairetemplate',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
