# Generated by Django 3.0.6 on 2020-08-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0034_auto_20200817_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_supervisor', models.BooleanField(blank=True, default=True, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyprofile',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='surveyprofile',
            name='is_interviewer',
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engagement.Supervisor'),
        ),
    ]
