# Generated by Django 3.0.6 on 2020-08-17 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0036_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairetemplate',
            name='locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='engagement.Supervisor'),
        ),
    ]
