# Generated by Django 2.1.15 on 2020-08-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0037_auto_20200817_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_supervisor',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='engagement.Employee'),
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
