# Generated by Django 2.1.15 on 2020-08-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0038_auto_20200820_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='cost_center',
            new_name='cost_center_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='cost_center_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
