# Generated by Django 3.0.6 on 2020-08-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0042_auto_20200826_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='css_class',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
