# Generated by Django 3.0.6 on 2020-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0043_section_css_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=80),
        ),
    ]
