# Generated by Django 2.1.15 on 2020-08-31 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0044_auto_20200826_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='css_class',
        ),
    ]
