# Generated by Django 3.1.2 on 2020-11-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0046_auto_20201109_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='descriptions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='rangedanswer',
            name='strings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
