# Generated by Django 3.1.2 on 2021-01-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0047_auto_20201109_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='evaluator',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
