# Generated by Django 3.1.1 on 2021-02-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0048_employee_evaluator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id']},
        ),
    ]
