# Generated by Django 3.1.1 on 2021-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0049_auto_20210204_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='helper',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
