# Generated by Django 3.1.1 on 2023-02-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0002_auto_20230202_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downtime', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DowntimeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RecordedDowntime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downtime_beginning', models.DateTimeField()),
                ('downtime_end', models.DateTimeField()),
                ('downtime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machining.downtime')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machining.machine')),
            ],
        ),
        migrations.AddField(
            model_name='downtime',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machining.downtimecategory'),
        ),
    ]
