# Generated by Django 3.1.1 on 2023-02-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machining', '0003_auto_20230214_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordeddowntime',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
