# Generated by Django 3.1.1 on 2022-08-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reman_2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='header',
            name='start_date',
        ),
    ]
