# Generated by Django 3.1.1 on 2022-08-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman_2', '0002_auto_20220830_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
