# Generated by Django 3.1.1 on 2022-08-31 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reman_2', '0004_auto_20220830_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='losses',
            name='assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losses_assembly', to='reman_2.material'),
        ),
        migrations.AddField(
            model_name='losses',
            name='damage',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='losses',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losses_material', to='reman_2.material'),
        ),
        migrations.AddField(
            model_name='losses',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
