# Generated by Django 3.1.1 on 2022-09-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reman_2', '0005_auto_20220831_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_material', to='reman_2.material')),
                ('secondary_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_material', to='reman_2.material')),
            ],
        ),
    ]
