# Generated by Django 3.1.1 on 2022-09-29 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reman_2', '0006_materialbinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootMaterialComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_material_quantity', models.IntegerField(default=0)),
                ('is_ignored', models.BooleanField(default=False)),
                ('is_manually_added', models.BooleanField(default=False)),
                ('is_manually_removed', models.BooleanField(default=False)),
                ('compound_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compound_material', to='reman_2.material')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_material', to='reman_2.material')),
            ],
        ),
        migrations.DeleteModel(
            name='MaterialBinding',
        ),
    ]
