# Generated by Django 3.1.1 on 2022-09-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman_2', '0007_auto_20220929_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_root_material',
            field=models.BooleanField(default=False),
        ),
    ]
