# Generated by Django 3.1.1 on 2022-09-29 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reman_2', '0010_auto_20220929_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootmaterialcomposition',
            name='material',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_material', to='reman_2.material'),
        ),
    ]
