# Generated by Django 3.1.1 on 2022-09-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reman_2', '0011_auto_20220929_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootmaterialcomposition',
            name='refreshed',
        ),
        migrations.AddField(
            model_name='material',
            name='refreshed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rootmaterialcomposition',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_material', to='reman_2.material'),
        ),
    ]
