# Generated by Django 3.1.1 on 2022-09-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman_2', '0012_auto_20220929_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='refreshed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
