# Generated by Django 3.1.1 on 2022-09-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reman_2', '0013_auto_20220929_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yfcorer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_shipment_id', models.IntegerField()),
                ('pallet_number', models.IntegerField()),
                ('core_return_item_number', models.IntegerField()),
                ('change_date', models.DateField()),
                ('core_inventory_flag', models.IntegerField()),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yfcorer_material', to='reman_2.material')),
            ],
        ),
    ]
