# Generated by Django 3.1.1 on 2022-09-29 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reman_2', '0014_yfcorer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('result', models.FloatField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reman_2.customer')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reman_2.material')),
                ('material_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reman_2.materialgroup')),
            ],
        ),
    ]
