# Generated by Django 3.1.1 on 2022-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reman_2', '0015_sortingresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
