# Generated by Django 3.1.1 on 2022-10-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reman_2', '0016_material_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='updated',
        ),
    ]
