# Generated by Django 3.1.2 on 2020-10-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0003_accidentsprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='accident_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='accident',
            name='accident_influenced_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='accident',
            name='accident_injury_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accident',
            name='employee_wrong',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='accident',
            name='workplace_wrong',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='accident',
            name='injury_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
