# Generated by Django 3.1.2 on 2020-10-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0005_hashedpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='protocol_author',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='witnesses',
        ),
        migrations.AddField(
            model_name='accident',
            name='witnesses',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
