# Generated by Django 3.1.2 on 2020-10-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0006_auto_20201027_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='fmea_implementation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='fmea_relevant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='measures_implementation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='sos_revision',
            field=models.DateField(blank=True, null=True),
        ),
    ]
