# Generated by Django 3.1.2 on 2020-10-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0007_auto_20201027_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='count_of_injured',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
