# Generated by Django 3.1.2 on 2020-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0008_auto_20201027_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='accident_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='hours_worked_before_accident',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='on_workplace_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='protocol_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
