# Generated by Django 3.1.2 on 2020-11-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0009_auto_20201027_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodypart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('bodypart', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InjuryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('injury_type', models.CharField(max_length=150)),
            ],
        ),
    ]
