# Generated by Django 3.1.2 on 2020-11-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0010_bodypart_injurytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearmiss',
            name='protocol_author_role',
            field=models.CharField(default='Ahoj', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nearmiss',
            name='protocol_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nearmiss',
            name='fmea_implementation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nearmiss',
            name='fmea_relevant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nearmiss',
            name='sos_revision',
            field=models.DateField(blank=True, null=True),
        ),
    ]
