# Generated by Django 3.1.2 on 2020-11-05 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accidents', '0012_auto_20201103_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='longterm_corrective_measures',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='measure_effectiveness',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='measures_implementation_date',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='status',
        ),
        migrations.RemoveField(
            model_name='nearmiss',
            name='longterm_corrective_measures',
        ),
        migrations.RemoveField(
            model_name='nearmiss',
            name='measure_effectiveness',
        ),
        migrations.RemoveField(
            model_name='nearmiss',
            name='measures_implementation_date',
        ),
        migrations.RemoveField(
            model_name='nearmiss',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='nearmiss',
            name='status',
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longterm_corrective_measures', models.CharField(max_length=500)),
                ('measures_implementation_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('measure_effectiveness', models.CharField(max_length=500)),
                ('accident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accidents.accident')),
                ('nearmiss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accidents.nearmiss')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
