# Generated by Django 3.1.2 on 2020-11-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0013_auto_20201105_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctiveaction',
            old_name='longterm_corrective_measures',
            new_name='longterm_corrective_measure',
        ),
    ]
