# Generated by Django 3.1.2 on 2020-11-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0016_auto_20201105_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveaction',
            name='longterm_corrective_measure',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
