# Generated by Django 3.1.2 on 2020-11-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0018_auto_20201105_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='changes_tracking',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='changes_tracking',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='nearmiss',
            name='changes_tracking',
            field=models.JSONField(default={}),
        ),
    ]
