# Generated by Django 3.1.2 on 2020-11-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0019_auto_20201105_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='changes_tracking',
        ),
        migrations.RemoveField(
            model_name='correctiveaction',
            name='changes_tracking',
        ),
        migrations.RemoveField(
            model_name='nearmiss',
            name='changes_tracking',
        ),
    ]
