# Generated by Django 3.1.1 on 2023-01-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0020_auto_20201105_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentsWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center_number', models.IntegerField()),
                ('personal_number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
