# Generated by Django 3.1.1 on 2023-01-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0021_accidentsworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentsworker',
            name='cost_center_number',
            field=models.CharField(max_length=32),
        ),
    ]
