# Generated by Django 3.1.1 on 2023-01-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0022_auto_20230111_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='injured',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accidents.accidentsworker'),
        ),
        migrations.AlterField(
            model_name='nearmiss',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accidents.accidentsworker'),
        ),
    ]
