# Generated by Django 3.1.1 on 2023-01-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0023_auto_20230111_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='accident_description',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accident_influenced_by',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accident_injury_type',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='activity_injury',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='area',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='employee_wrong',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='immediate_corrective_measures',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='injured_bodypart',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='injured_role',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='accident',
            name='injury_classification',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accident',
            name='injury_description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='injury_launcher',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='injury_rootcause',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='injury_rootcause_type',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='injury_type',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='place',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='protocol_author_role',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='witnesses',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='accident',
            name='workplace_wrong',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='accidentsworker',
            name='cost_center_number',
            field=models.CharField(max_length=320),
        ),
        migrations.AlterField(
            model_name='accidentsworker',
            name='name',
            field=models.CharField(blank=True, max_length=1280),
        ),
        migrations.AlterField(
            model_name='bodypart',
            name='bodypart',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='measure_effectiveness',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='responsible',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='hashedpicture',
            name='filename',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='hashedpicture',
            name='hashed_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='injurytype',
            name='injury_type',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='nearmiss',
            name='activity_nearmiss',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='nearmiss',
            name='area',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nearmiss',
            name='immediate_corrective_measures',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='nearmiss',
            name='nearmiss_description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='nearmiss',
            name='nearmiss_launcher',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='nearmiss',
            name='nearmiss_rootcause',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='nearmiss',
            name='place',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nearmiss',
            name='protocol_author_role',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nearmiss',
            name='reporter_role',
            field=models.CharField(max_length=500),
        ),
    ]
