# Generated by Django 2.1.7 on 2020-09-03 19:12

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_car', models.BooleanField(default=False)),
                ('manager_car', models.BooleanField(default=False)),
                ('car_manufacturer', models.CharField(max_length=50)),
                ('car_make', models.CharField(max_length=50)),
                ('car_license_plate', models.CharField(max_length=20)),
                ('car_mileage', models.IntegerField()),
                ('car_status', models.CharField(max_length=30)),
                ('car_information', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_datetime_start', models.DateTimeField()),
                ('reservation_datetime_end', models.DateTimeField()),
                ('reservation_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reserved_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.Car')),
            ],
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='car_accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.Car'),
        ),
    ]
