# Generated by Django 2.1.7 on 2020-09-03 19:24

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_datetime', models.DateTimeField()),
                ('car_fuel', models.IntegerField()),
                ('car_cleannes', models.IntegerField()),
                ('car_damage', models.CharField(max_length=500)),
                ('car_information', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ReturnReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_datetime', models.DateTimeField()),
                ('car_fuel', models.IntegerField()),
                ('car_cleannes', models.IntegerField()),
                ('car_damage', models.CharField(max_length=500)),
                ('return_information', django.contrib.postgres.fields.jsonb.JSONField()),
                ('return_receptionist', models.CharField(max_length=40)),
                ('return_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='accidentreport',
            old_name='car_accident',
            new_name='accident_car',
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='accident_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_information',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnreport',
            name='returned_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.Car'),
        ),
        migrations.AddField(
            model_name='pickupreport',
            name='pickup_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.Car'),
        ),
        migrations.AddField(
            model_name='pickupreport',
            name='pickup_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
