# Generated by Django 2.1.7 on 2020-09-04 17:47

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpool', '0002_auto_20200903_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carloan_start', models.DateTimeField(blank=True, null=True)),
                ('carloan_end', models.DateTimeField(blank=True, null=True)),
                ('car_loaner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='accident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='accident_information',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='accident_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='car_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='accident_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.Car'),
        ),
        migrations.AlterField(
            model_name='pickupreport',
            name='pickup_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.Car'),
        ),
        migrations.AlterField(
            model_name='pickupreport',
            name='pickup_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.Car'),
        ),
        migrations.AlterField(
            model_name='returnreport',
            name='return_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnreport',
            name='returned_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.Car'),
        ),
        migrations.AddField(
            model_name='carloan',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.Reservation'),
        ),
        migrations.AddField(
            model_name='pickupreport',
            name='carloan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.CarLoan'),
        ),
        migrations.AddField(
            model_name='returnreport',
            name='carloan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.CarLoan'),
        ),
    ]
