# Generated by Django 2.1.7 on 2020-09-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0006_carprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_consumption_real',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_consumption_theoretical',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SPZ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='PIN'),
        ),
        migrations.AlterField(
            model_name='car',
            name='shell_kb_number',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Shell KB číslo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='shell_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Shell číslo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='technical_certificate',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Číslo technického průkazu'),
        ),
    ]
