# Generated by Django 2.1.7 on 2020-09-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0007_auto_20200908_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
