# Generated by Django 2.1.7 on 2020-09-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0008_auto_20200908_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_reserved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
