# Generated by Django 2.1.7 on 2020-09-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0010_auto_20200917_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupreport',
            name='car_cleannes',
        ),
        migrations.AddField(
            model_name='pickupreport',
            name='car_exterior_cleannes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickupreport',
            name='car_interior_cleannes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_consumption_real',
            field=models.FloatField(blank=True, null=True, verbose_name='Spotřeba reální'),
        ),
        migrations.AlterField(
            model_name='pickupreport',
            name='car_fuel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
