# Generated by Django 2.1.7 on 2020-09-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0011_auto_20200918_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupreport',
            name='car_information',
        ),
    ]
