# Generated by Django 3.0.6 on 2020-09-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0014_carloan_carloan_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carloan',
            name='carloan_message',
        ),
        migrations.AddField(
            model_name='pickupreport',
            name='pickupreport_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
