# Generated by Django 2.1.7 on 2020-09-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0015_auto_20200921_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnreport',
            name='return_information',
        ),
        migrations.AddField(
            model_name='returnreport',
            name='returnreport_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
