# Generated by Django 2.1.7 on 2020-09-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0016_auto_20200921_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupreport',
            name='pickupreport_message',
        ),
        migrations.RemoveField(
            model_name='returnreport',
            name='car_cleannes',
        ),
        migrations.RemoveField(
            model_name='returnreport',
            name='car_fuel',
        ),
        migrations.RemoveField(
            model_name='returnreport',
            name='returnreport_message',
        ),
        migrations.AlterField(
            model_name='returnreport',
            name='return_receptionist',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
