# Generated by Django 2.1.7 on 2020-09-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0017_auto_20200921_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='carloan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.CarLoan'),
        ),
    ]
