# Generated by Django 2.1.7 on 2020-09-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0018_accidentreport_carloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('accident_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.AccidentReport')),
            ],
        ),
    ]
