# Generated by Django 3.1.1 on 2020-09-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0019_accidentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='accident_information',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_history',
            field=models.JSONField(blank=True, null=True, verbose_name='Historie'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_information',
            field=models.JSONField(blank=True, null=True, verbose_name='Informace'),
        ),
    ]
