# Generated by Django 3.1.1 on 2020-10-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0021_carloan_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carloan',
            name='urls',
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='urls',
            field=models.JSONField(default={}),
        ),
    ]
