# Generated by Django 3.1.1 on 2020-10-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0023_accidentreport_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentreport',
            name='accident_information',
        ),
        migrations.AddField(
            model_name='carloan',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
