# Generated by Django 3.1.1 on 2020-10-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0024_auto_20201013_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='driver_role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
