# Generated by Django 3.1.1 on 2020-10-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0026_reservation_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_costs', models.FloatField()),
                ('repair_start', models.DateTimeField(blank=True, null=True)),
                ('repair_end', models.DateTimeField(blank=True, null=True)),
                ('caused_by_accident', models.BooleanField(default=False)),
                ('caused_by_wear', models.BooleanField(default=False)),
                ('srm_number', models.CharField(max_length=50)),
                ('pending_confirmation', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('carloan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.carloan')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='repair_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AccidentImage',
        ),
    ]
