# Generated by Django 3.1.1 on 2020-10-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0027_auto_20201014_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrepair',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrepair',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.car'),
        ),
        migrations.AddField(
            model_name='carrepair',
            name='pending_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrepair',
            name='sent_to_service',
            field=models.BooleanField(default=False),
        ),
    ]
