# Generated by Django 3.1.1 on 2020-10-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0028_auto_20201014_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrepair',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
