# Generated by Django 3.1.1 on 2020-10-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0029_carrepair_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='carprofile',
            name='manager',
        ),
        migrations.AddField(
            model_name='carprofile',
            name='can_approve_accident',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='carprofile',
            name='can_close_accident',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='carprofile',
            name='can_confirm_accident',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='carrepair',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='carrepair',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
