# Generated by Django 3.1.1 on 2020-10-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0030_auto_20201014_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrepair',
            name='pending_closure',
            field=models.BooleanField(default=False),
        ),
    ]
