# Generated by Django 3.1.1 on 2020-10-16 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpool', '0035_auto_20201016_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carloan',
            name='repair_loan',
        ),
        migrations.AddField(
            model_name='reservation',
            name='repair_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
