# Generated by Django 3.1.1 on 2020-10-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0036_auto_20201016_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrepair',
            name='notes',
            field=models.CharField(blank=True, max_length=3500, null=True),
        ),
    ]
