# Generated by Django 3.1.1 on 2020-10-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0037_carrepair_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrepair',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.reservation'),
        ),
    ]
