# Generated by Django 3.1.1 on 2020-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0038_carrepair_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrepair',
            name='cost_estimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrepair',
            name='repair_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
