# Generated by Django 3.1.1 on 2020-10-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0039_auto_20201019_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrepair',
            name='pending_approval',
        ),
        migrations.RemoveField(
            model_name='carrepair',
            name='pending_closure',
        ),
        migrations.RemoveField(
            model_name='carrepair',
            name='pending_confirmation',
        ),
        migrations.RemoveField(
            model_name='carrepair',
            name='sent_to_service',
        ),
        migrations.AddField(
            model_name='carprofile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
