# Generated by Django 3.1.1 on 2020-10-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0041_auto_20201020_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='carprofile',
            name='regular_user',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
