# Generated by Django 3.1.1 on 2020-10-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0042_carprofile_regular_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_reservation', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='carprofile',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='carprofile',
            name='closer',
        ),
        migrations.RemoveField(
            model_name='carprofile',
            name='confirmer',
        ),
        migrations.RemoveField(
            model_name='carprofile',
            name='regular_user',
        ),
        migrations.AddField(
            model_name='carprofile',
            name='user_roles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
