# Generated by Django 3.1.1 on 2020-10-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0043_auto_20201020_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermissions',
            name='approve_repair',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='close_repair',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='confirm_repair',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='create_accident',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='create_repair',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='edit_carpark',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
