# Generated by Django 3.1.1 on 2020-10-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0044_auto_20201020_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='destination',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='kilometres',
            field=models.IntegerField(null=True),
        ),
    ]
