# Generated by Django 3.1.1 on 2020-10-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0045_auto_20201021_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='next_service_kms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='technical_control_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
