# Generated by Django 3.1.1 on 2020-10-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0046_auto_20201021_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='kms_status_current_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
