# Generated by Django 3.1.2 on 2020-10-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0047_car_kms_status_current_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='urls',
            field=models.JSONField(default=dict),
        ),
    ]
