# Generated by Django 3.1.1 on 2022-05-31 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0049_auto_20220530_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carpool/pickup_images/')),
                ('field', models.CharField(max_length=64)),
                ('pickup_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.pickupreport')),
            ],
        ),
    ]
