# Generated by Django 3.1.1 on 2022-06-06 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0050_pickupimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupreport',
            name='tank',
        ),
        migrations.RemoveField(
            model_name='returnreport',
            name='return_person',
        ),
        migrations.RemoveField(
            model_name='returnreport',
            name='return_receptionist',
        ),
        migrations.RemoveField(
            model_name='returnreport',
            name='returned_car',
        ),
        migrations.AddField(
            model_name='pickupreport',
            name='tachometer_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pickupreport',
            name='tank_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='returnreport',
            name='tachometer_value',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_bought_amount', models.IntegerField()),
                ('fuel_bought_sum', models.FloatField()),
                ('carloan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.carloan')),
            ],
        ),
    ]
