# Generated by Django 3.1.1 on 2022-06-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0051_auto_20220606_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupreport',
            name='notes',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
