# Generated by Django 3.1.1 on 2022-06-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0053_auto_20220606_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupPermissions',
        ),
        migrations.RemoveField(
            model_name='carprofile',
            name='user_roles',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='sequence',
        ),
        migrations.AddField(
            model_name='carprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
