# Generated by Django 3.1.1 on 2022-06-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0054_auto_20220610_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_creator',
            new_name='reservation_user',
        ),
    ]
