# Generated by Django 3.1.1 on 2022-06-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0056_auto_20220615_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tachometer_value',
            field=models.IntegerField(null=True),
        ),
    ]
