# Generated by Django 3.1.2 on 2022-06-21 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0058_remove_car_tachometer_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_license_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='SPZ')),
                ('car_mileage', models.IntegerField(blank=True, null=True, verbose_name='Stav km')),
                ('reservation_datetime_start', models.DateTimeField()),
                ('reservation_datetime_end', models.DateTimeField()),
                ('return_datetime', models.DateTimeField()),
                ('part_damaged', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=3500, null=True)),
                ('carloan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.carloan')),
            ],
        ),
    ]
