# Generated by Django 3.1.2 on 2022-06-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0060_damagereports_repair_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damagereports',
            options={'managed': False},
        ),
    ]
