# Generated by Django 3.1.2 on 2022-06-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0061_auto_20220621_1105'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='damagereports',
            table='DamageReports',
        ),
    ]
