# Generated by Django 3.1.2 on 2022-06-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0062_auto_20220621_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damagereports',
            options={},
        ),
    ]
