# Generated by Django 3.1.1 on 2022-06-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0063_auto_20220621_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='kms_yearly',
        ),
        migrations.AddField(
            model_name='car',
            name='active_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='kms_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Km v leasingu'),
        ),
    ]
