# Generated by Django 3.1.2 on 2021-02-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QM02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=16, null=True)),
                ('q2_report_number', models.CharField(blank=True, max_length=16, null=True)),
                ('excel_row', models.IntegerField(blank=True, null=True)),
                ('total_costs', models.FloatField(blank=True, null=True)),
                ('line_loss', models.FloatField(blank=True, null=True)),
                ('responsible_department', models.CharField(blank=True, max_length=16, null=True)),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('reduction', models.FloatField(blank=True, null=True)),
                ('to_be_invoiced', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
