# Generated by Django 3.1.2 on 2021-02-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qm02',
            name='other_costs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qm02',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
