# Generated by Django 3.1.2 on 2021-02-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_auto_20210210_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='qm02',
            name='uploaded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
