# Generated by Django 3.1.2 on 2021-03-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_auto_20210219_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qm02',
            old_name='item_category',
            new_name='extra_costs_code',
        ),
        migrations.RenameField(
            model_name='qm02',
            old_name='comment',
            new_name='reason_comment',
        ),
        migrations.AddField(
            model_name='qm02',
            name='qm_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
