# Generated by Django 3.1.1 on 2021-03-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_auto_20210305_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='qm02',
            name='reason_long_text',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
