# Generated by Django 3.1.2 on 2022-02-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='usage_description',
        ),
        migrations.AddField(
            model_name='part',
            name='matchode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='station',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='usage_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='delivery_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='electrical',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='mechanical',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
