# Generated by Django 3.1.2 on 2022-02-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20220204_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='manufacturer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
