# Generated by Django 3.1.2 on 2022-02-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20220204_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='label_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.part'),
        ),
    ]
