# Generated by Django 3.1.2 on 2022-02-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20220204_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='label_2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
