# Generated by Django 3.1.2 on 2022-02-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_auto_20220204_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='manufacturing_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='sap_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
