# Generated by Django 3.1.1 on 2022-02-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_auto_20220204_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawSparePartsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_description', models.CharField(max_length=255, null=True)),
                ('label_2', models.CharField(max_length=255, null=True)),
                ('manufacturing_number', models.CharField(max_length=255, null=True)),
                ('label_1', models.CharField(max_length=255, null=True)),
                ('manufacturer', models.CharField(max_length=255, null=True)),
                ('sap_number', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('electrical', models.BooleanField(null=True)),
                ('mechanical', models.BooleanField(null=True)),
                ('price', models.FloatField(null=True)),
                ('delivery_time', models.IntegerField(null=True)),
                ('recommended_part', models.BooleanField(null=True)),
                ('produced_part', models.BooleanField(null=True)),
                ('criticality', models.CharField(max_length=16, null=True)),
                ('wearable', models.BooleanField(null=True)),
                ('safety_stock', models.CharField(max_length=16, null=True)),
                ('documentation_label', models.CharField(max_length=255, null=True)),
                ('line', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
