# Generated by Django 3.1.1 on 2022-02-09 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_rawsparepartslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spareparts',
            name='line',
        ),
        migrations.AddField(
            model_name='spareparts',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.line'),
        ),
    ]
