# Generated by Django 3.1.1 on 2022-02-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_rawsparepartslist_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawsparepartslist',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
