# Generated by Django 3.1.1 on 2022-02-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_auto_20220209_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='position',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
