# Generated by Django 3.1.2 on 2022-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_auto_20220209_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='matchode',
            new_name='matchcode',
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
