# Generated by Django 3.1.1 on 2022-02-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_auto_20220222_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RawSparePartsList',
        ),
    ]
