# Generated by Django 3.1.1 on 2022-02-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_delete_rawsparepartslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
