# Generated by Django 3.1.2 on 2022-02-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_uservisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='columns',
            name='visible_by_default',
            field=models.BooleanField(default=False),
        ),
    ]
