# Generated by Django 3.1.1 on 2022-03-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_auto_20220302_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='columns',
            name='is_boolean',
            field=models.BooleanField(default=False),
        ),
    ]
