# Generated by Django 3.1.1 on 2022-03-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_auto_20220302_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
