# Generated by Django 3.1.1 on 2022-03-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_auto_20220303_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='quantity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
