# Generated by Django 3.0.5 on 2020-04-27 08:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_number', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('prod_unit', models.CharField(max_length=20)),
                ('SMI', models.CharField(max_length=80)),
                ('assignments', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerAvailableWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('shift', models.CharField(max_length=20)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burza.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('target_prod_unit', models.CharField(max_length=20)),
                ('approved_by_lender', models.BooleanField()),
                ('approved_by_borrower', models.BooleanField()),
                ('realised', models.BooleanField()),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burza.WorkerAvailableWindow')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burza.Worker')),
            ],
        ),
    ]
