# Generated by Django 3.0.5 on 2020-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0002_auto_20200427_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('shift', models.CharField(max_length=20)),
                ('target_prod_unit', models.CharField(max_length=20)),
                ('fullfiled', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='WorkerAvailableWindow',
            new_name='AvailableWindow',
        ),
    ]
