# Generated by Django 3.0.5 on 2020-04-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0003_auto_20200427_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableWindow',
            new_name='Offer',
        ),
        migrations.RenameModel(
            old_name='Requirement',
            new_name='Request',
        ),
    ]
