# Generated by Django 3.0.5 on 2020-04-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0004_auto_20200428_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='SMI',
            new_name='manager',
        ),
    ]
