# Generated by Django 3.0.5 on 2020-04-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0007_auto_20200428_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='manager',
            field=models.CharField(default='N/A', max_length=80),
        ),
    ]
