# Generated by Django 3.0.5 on 2020-04-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0010_auto_20200428_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='fullfiled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='fullfiled',
            field=models.BooleanField(default=False),
        ),
    ]
