# Generated by Django 3.0.5 on 2020-04-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0011_auto_20200428_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='window',
            new_name='offer',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='approved_by_borrower',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='approved_by_lender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='realised',
            field=models.BooleanField(default=False),
        ),
    ]
