# Generated by Django 3.0.5 on 2020-05-05 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0013_auto_20200428_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='burza.Request'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='burza.Offer'),
        ),
    ]
