# Generated by Django 3.0.6 on 2020-06-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0014_auto_20200505_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='supervisor',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='personal_number',
            field=models.IntegerField(unique=True),
        ),
    ]
