# Generated by Django 3.0.6 on 2020-06-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0015_auto_20200603_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='burza.Worker', to_field='personal_number'),
        ),
    ]
