# Generated by Django 3.0.6 on 2020-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0016_auto_20200603_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='cost_center',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
