# Generated by Django 3.0.6 on 2020-06-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0017_worker_cost_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='assignments',
        ),
    ]
