# Generated by Django 3.0.6 on 2020-06-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0018_remove_worker_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='prod_unit',
        ),
    ]
