# Generated by Django 3.0.6 on 2020-06-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0021_auto_20200603_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='is_manager',
            new_name='is_teamleader',
        ),
    ]
