# Generated by Django 3.0.6 on 2020-06-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0024_auto_20200604_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='managed_ccs',
        ),
    ]
