# Generated by Django 3.0.6 on 2020-06-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0026_remove_worker_not_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindings',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burza.Worker', to_field='personal_number'),
        ),
    ]
