# Generated by Django 3.0.6 on 2020-06-04 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0027_auto_20200604_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindings',
            name='manager_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_1', to='burza.Worker'),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
