# Generated by Django 3.0.6 on 2020-06-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0029_auto_20200604_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='not_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
