# Generated by Django 3.0.6 on 2020-06-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0030_worker_not_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='approved_by_borrower',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='approved_by_lender',
        ),
    ]
