# Generated by Django 3.0.6 on 2020-06-17 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0031_auto_20200604_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burza.Assignment')),
            ],
        ),
        migrations.DeleteModel(
            name='Bindings',
        ),
    ]
