# Generated by Django 3.0.6 on 2020-06-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0032_auto_20200617_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='pending_cancellation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='pending_cancellation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
