# Generated by Django 3.0.6 on 2020-06-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0033_auto_20200617_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='declined',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
