# Generated by Django 3.0.6 on 2020-07-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0037_request_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('costcenter_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='costcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='burza.CostCenter'),
        ),
    ]
