# Generated by Django 3.0.6 on 2020-07-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0038_auto_20200721_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='realised',
            field=models.BooleanField(default=True),
        ),
    ]
