# Generated by Django 3.0.6 on 2020-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0039_auto_20200721_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='costcenter_name',
            field=models.CharField(max_length=50),
        ),
    ]
