# Generated by Django 3.0.6 on 2020-07-21 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0040_auto_20200721_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burza.Worker', to_field='personal_number'),
        ),
    ]
