# Generated by Django 3.0.6 on 2020-07-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0042_auto_20200721_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costcenter',
            old_name='costcenter_name',
            new_name='name',
        ),
    ]
