# Generated by Django 3.0.6 on 2020-07-21 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0044_auto_20200721_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='target_cost_center',
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_costcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='burza.CostCenter'),
        ),
    ]
