# Generated by Django 2.1.15 on 2020-07-22 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0047_burzauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burzauser',
            name='burza_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='burza_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
