# Generated by Django 3.0.6 on 2020-07-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0048_auto_20200722_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='end',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='start',
            field=models.FloatField(default=0),
        ),
    ]
