# Generated by Django 3.0.6 on 2020-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0049_auto_20200723_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start',
            field=models.IntegerField(default=0),
        ),
    ]
