# Generated by Django 3.0.6 on 2020-07-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0051_auto_20200723_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end',
            field=models.DateTimeField(blank=True, default='2020-12-31 10:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='start',
            field=models.DateTimeField(blank=True, default='2020-12-31 10:00:00'),
            preserve_default=False,
        ),
    ]
