# Generated by Django 3.0.6 on 2020-07-23 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0054_auto_20200723_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 7, 23)),
        ),
        migrations.AddField(
            model_name='offer',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 7, 23)),
        ),
    ]
