# Generated by Django 3.0.6 on 2020-07-28 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0057_auto_20200723_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 7, 28)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 7, 28)),
        ),
        migrations.AlterField(
            model_name='request',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 7, 28)),
        ),
        migrations.AlterField(
            model_name='request',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 7, 28)),
        ),
    ]
