# Generated by Django 3.0.6 on 2020-07-28 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0058_auto_20200728_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
