# Generated by Django 2.1.15 on 2020-08-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0061_auto_20200831_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_start',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
