# Generated by Django 2.1.7 on 2020-09-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0062_auto_20200831_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='burza.Worker'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='burza.Worker'),
        ),
    ]
