# Generated by Django 2.1.7 on 2020-09-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burza', '0065_auto_20200904_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='left',
            field=models.BooleanField(default=False),
        ),
    ]
