# Generated by Django 3.1.1 on 2022-08-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partno', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThingworxLocalsmartkpi',
        ),
    ]
